# Generated by Django 4.1 on 2022-10-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upfile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="arquivo", name="descricao",),
        migrations.RemoveField(model_name="arquivo", name="email",),
        migrations.RemoveField(model_name="arquivo", name="nome",),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True, max_length=300)),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="upfile.arquivo",
                    ),
                ),
            ],
        ),
    ]
