# Generated by Django 4.1 on 2022-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upfile", "0002_remove_arquivo_descricao_remove_arquivo_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(upload_to="files/%Y/%m/"),
        ),
    ]
